name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'

jobs:
  # run tests
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Run server locally
        env:
          PORT: 5000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn start &

      - name: Run tests
        run: yarn test
