name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'

jobs:
  # run tests
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Echo something
        run: echo "Hello World. Here I will run some tests. :3"
